"""Phase 3: エンティティ skeleton 生成 + 日次ノート集約 + 一覧再生成。

役割:
- 録音ノートに現れた [[人物]] [[トピック]] [[場所]] の Vault 内ノートを
  存在しなければ skeleton (自動生成マーカー付き) で作成する
- その日の 録音/YYYY-MM-DD/*.md を集約して 日次/YYYY-MM-DD.md を再生成する
- Vault 全体をスキャンして 一覧/ToDo.md と 一覧/重要度高.md を再生成する

Phase 2 と独立して呼べる:
- main.py から _run_structuring の直後に呼ぶ
- `python main.py aggregate` で既存ノートから再生成だけする
"""
from __future__ import annotations

import re
from collections.abc import Iterable
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml

import reminders
from config import Config


_SKELETON_MARKER = "<!-- auto-skeleton -->"
_GENERATED_MARKER = "<!-- auto-generated by aggregator.py -->"

_PERSON_DIR = "人物"
_TOPIC_DIR = "トピック"
_LOCATION_DIR = "場所"
_DAILY_DIR = "日次"
_INDEX_DIR = "一覧"
_NOTES_SUBDIR = "録音"


# -------------------- 共通ユーティリティ --------------------


def _strip_wikilink(s: str) -> str:
    """`[[田中さん]]` → `田中さん`。素のままならそのまま返す。
    `[[人物/田中さん|表示]]` → `田中さん`(パイプ前のラベルから最後のスラッシュ以降を採用)。"""
    if not s:
        return ""
    s = s.strip()
    m = re.fullmatch(r"\[\[(.+?)\]\]", s)
    if m:
        s = m.group(1)
    if "|" in s:
        s = s.split("|", 1)[0]
    if "/" in s:
        s = s.rsplit("/", 1)[-1]
    return s.strip()


def _sanitize_filename(name: str) -> str:
    """OS のファイル名に使えない文字を除く。空になったら None 相当扱い。"""
    name = name.strip()
    # Windows/Obsidian で問題になる文字
    for ch in '<>:"/\\|?*':
        name = name.replace(ch, "_")
    # 先頭・末尾の空白とピリオドは禁止
    name = name.strip(" .")
    return name


def _parse_note(path: Path) -> tuple[dict, str]:
    """ノートを (frontmatter, body) に分割。
    frontmatter が無ければ ({}, 全文)。
    パース失敗時も例外を投げず、frontmatter は {} で返す。"""
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return {}, ""
    if not text.startswith("---\n"):
        return {}, text
    end = text.find("\n---", 4)
    if end == -1:
        return {}, text
    fm_text = text[4:end]
    body = text[end + 4 :].lstrip("\n")
    try:
        fm = yaml.safe_load(fm_text) or {}
    except yaml.YAMLError:
        fm = {}
    if not isinstance(fm, dict):
        fm = {}
    return fm, body


def _list_recording_notes(cfg: Config) -> list[Path]:
    """録音/YYYY-MM-DD/HH-MM-SS.md を全て列挙(日付・時刻順)。"""
    base = cfg.vault / _NOTES_SUBDIR
    if not base.exists():
        return []
    out: list[Path] = []
    for day_dir in sorted(base.iterdir()):
        if not day_dir.is_dir():
            continue
        for f in sorted(day_dir.glob("*.md")):
            out.append(f)
    return out


def _list_recording_notes_for_date(cfg: Config, date: str) -> list[Path]:
    base = cfg.vault / _NOTES_SUBDIR / date
    if not base.exists():
        return []
    return sorted(base.glob("*.md"))


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


# -------------------- ① エンティティ skeleton 生成 --------------------


def _collect_entities(
    structured: dict,
) -> dict[str, list[str]]:
    """structured 結果から `人物` `トピック` `場所` のユニークなリストを得る。
    [[]] が付いていれば剥がす。"""
    out: dict[str, list[str]] = {_PERSON_DIR: [], _TOPIC_DIR: [], _LOCATION_DIR: []}
    seen: dict[str, set[str]] = {k: set() for k in out}
    contexts = structured.get("contexts") or []
    mapping = {
        "counterpart": _PERSON_DIR,
        "topics": _TOPIC_DIR,
        "locations": _LOCATION_DIR,
    }
    for c in contexts:
        if not isinstance(c, dict):
            continue
        for field, kind in mapping.items():
            for item in c.get(field, []) or []:
                if not item:
                    continue
                name = _strip_wikilink(str(item))
                name = _sanitize_filename(name)
                if not name or name in seen[kind]:
                    continue
                seen[kind].add(name)
                out[kind].append(name)
    return out


def _skeleton_body(kind: str, name: str) -> str:
    """人物/トピック/場所 ノートの初期内容。後で手動編集される前提。"""
    fm = {
        "type": kind,
        "name": name,
        "created": datetime.now(timezone.utc).date().isoformat(),
        "tags": [kind],
    }
    fm_text = yaml.safe_dump(
        fm, allow_unicode=True, sort_keys=False, default_flow_style=False
    ).rstrip()

    if kind == _PERSON_DIR:
        hint = "## メモ\n\n(関係性・所属・連絡先などを追記)\n"
    elif kind == _TOPIC_DIR:
        hint = "## メモ\n\n(案件・テーマの背景や論点を追記)\n"
    else:  # 場所
        hint = "## メモ\n\n(住所・特徴などを追記)\n"

    return (
        f"---\n{fm_text}\n---\n\n"
        f"{_SKELETON_MARKER}\n\n"
        f"# {name}\n\n"
        f"> このノートはパイプラインが自動生成した skeleton です。情報を追記してください。\n\n"
        f"{hint}\n"
        f"## 関連録音\n\n"
        f"(Obsidian のバックリンクに自動表示されます)\n"
    )


def ensure_entity_skeletons(
    structured: dict, cfg: Config
) -> dict[str, list[str]]:
    """構造化結果に含まれる人物・トピック・場所の skeleton ノートを必要なら作成する。

    既に存在するノートは触らない(skeleton かどうかも関係なく)。
    返り値: 種別ごとの「今回新規に作成した」名前リスト。"""
    created: dict[str, list[str]] = {_PERSON_DIR: [], _TOPIC_DIR: [], _LOCATION_DIR: []}
    if not structured:
        return created

    entities = _collect_entities(structured)
    for kind, names in entities.items():
        target_dir = cfg.vault / kind
        for name in names:
            target = target_dir / f"{name}.md"
            if target.exists():
                continue
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(_skeleton_body(kind, name), encoding="utf-8")
            created[kind].append(name)
    return created


# -------------------- ② 日次ノート集約 --------------------


def _extract_todos(body: str) -> list[dict]:
    """ノート本文から `- [ ] ...` 行(`#todo` タグ前提)を抽出。
    `(期限: YYYY-MM-DD)` を `due` に分離する。完了 (`- [x]`) は除外。"""
    out: list[dict] = []
    pattern = re.compile(r"^-\s+\[ \]\s+(.*?)\s*$")
    due_pattern = re.compile(r"\(期限:\s*([^)]+)\)")
    for line in body.splitlines():
        m = pattern.match(line)
        if not m:
            continue
        text = m.group(1)
        if "#todo" not in text:
            # アグリゲータでは #todo タグが無い ToDo も拾うが、明示しておく
            pass
        # #todo タグ、末尾の @assignee を整形に使えるが、ここでは生のテキストでよい
        due = None
        dm = due_pattern.search(text)
        if dm:
            due = dm.group(1).strip()
        text_clean = due_pattern.sub("", text).replace("#todo", "").strip()
        out.append({"text": text_clean, "due": due, "raw": text})
    return out


def _note_link(note_path: Path, cfg: Config, label: str | None = None) -> str:
    """`録音/2026-05-23/13-39-19.md` への wikilink。
    Obsidian の wikilink はベース名で動くが、ここでは曖昧さ回避のため
    `録音/YYYY-MM-DD/HH-MM-SS` で書く。"""
    rel = note_path.relative_to(cfg.vault).with_suffix("")
    target = rel.as_posix()
    if label:
        return f"[[{target}|{label}]]"
    return f"[[{target}]]"


def _summarize_note(fm: dict, body: str) -> str:
    """日次集約用に1行サマリを作る。

    body に `### 要約` セクションがあれば最初の段落を採る、無ければ frontmatter title 系。"""
    summary = ""
    lines = body.splitlines()
    in_summary = False
    buf: list[str] = []
    for line in lines:
        if line.startswith("### 要約"):
            in_summary = True
            continue
        if in_summary:
            if not line.strip():
                if buf:
                    break
                continue
            if line.startswith("#"):
                break
            buf.append(line.strip())
    if buf:
        summary = " ".join(buf)
    if not summary:
        # フォールバック: 最初の `## ` heading 直後の本文
        for i, line in enumerate(lines):
            if line.startswith("## ") and i + 1 < len(lines):
                rest = lines[i + 1 : i + 4]
                summary = " ".join(s for s in rest if s.strip())
                if summary:
                    break
    # 長すぎる場合は切る
    if len(summary) > 120:
        summary = summary[:117] + "…"
    return summary


def _normalize_time_value(raw: Any, fallback_stem: str) -> str:
    """frontmatter の time 値を `HH:MM:SS` に寄せる。

    YAML 1.1 は `13:39:19` を sexagesimal int(49159)としてパースしてしまうので、
    int で来た場合も復元する。失敗時は fallback_stem (HH-MM-SS) を `:` 区切りに。"""
    if isinstance(raw, str) and raw:
        return raw
    if isinstance(raw, int) and raw >= 0:
        h, rem = divmod(raw, 3600)
        m, s = divmod(rem, 60)
        if 0 <= h < 24:
            return f"{h:02d}:{m:02d}:{s:02d}"
    fallback = fallback_stem.replace("-", ":")
    return fallback


def _parse_recording_meta(fm: dict, path: Path) -> dict:
    """録音ノートの frontmatter から日次/一覧用のメタ情報を取り出す。"""
    date_raw = fm.get("date")
    date = str(date_raw) if date_raw else path.parent.name
    time = _normalize_time_value(fm.get("time"), path.stem)
    importance = fm.get("importance")
    try:
        importance = int(importance) if importance is not None else 0
    except (TypeError, ValueError):
        importance = 0
    domains = [str(d) for d in (fm.get("domains") or []) if d]
    counterpart = [_strip_wikilink(str(c)) for c in (fm.get("counterpart") or []) if c]
    topics = [_strip_wikilink(str(t)) for t in (fm.get("topics") or []) if t]
    locations = [_strip_wikilink(str(l)) for l in (fm.get("locations") or []) if l]
    return {
        "path": path,
        "date": date,
        "time": time,
        "time_short": time[:5] if len(time) >= 5 else time,
        "importance": importance,
        "domains": domains,
        "counterpart": counterpart,
        "topics": topics,
        "locations": locations,
    }


def _render_daily_note(date: str, recordings: list[dict], cfg: Config) -> str:
    """日次ノートの本文を組み立てる。"""
    total = len(recordings)
    important = [r for r in recordings if r["importance"] >= 4]
    all_todos: list[tuple[dict, dict]] = []  # (recording, todo)
    for r in recordings:
        _, body = _parse_note(r["path"])
        for todo in _extract_todos(body):
            all_todos.append((r, todo))

    fm = {
        "date": date,
        "type": "日次",
        "tags": ["日次"],
        "recordings": total,
        "important": len(important),
        "todos": len(all_todos),
        "generated_at": _now_iso(),
    }
    fm_text = yaml.safe_dump(
        fm, allow_unicode=True, sort_keys=False, default_flow_style=False
    ).rstrip()

    lines: list[str] = []
    lines.append("---")
    lines.append(fm_text)
    lines.append("---")
    lines.append("")
    lines.append(_GENERATED_MARKER)
    lines.append("")
    lines.append(f"# {date}")
    lines.append("")
    if total == 0:
        lines.append("録音なし。")
        lines.append("")
        return "\n".join(lines) + "\n"

    lines.append(
        f"録音 {total} 件 / 重要度高 {len(important)} 件 / ToDo {len(all_todos)} 件"
    )
    lines.append("")

    lines.append("## 録音")
    for r in recordings:
        fm_r, body_r = _parse_note(r["path"])
        summary = _summarize_note(fm_r, body_r)
        link = _note_link(r["path"], cfg)
        bits = [f"- {r['time_short']} {link}"]
        if summary:
            bits.append(f"— {summary}")
        tag_bits = []
        for d in r["domains"]:
            tag_bits.append(f"#{d}")
        if r["importance"] >= 4:
            tag_bits.append(f"重要度{r['importance']}")
        if tag_bits:
            bits.append(" ".join(tag_bits))
        lines.append(" ".join(bits))
    lines.append("")

    if all_todos:
        lines.append("## ToDo")
        for r, todo in all_todos:
            link = _note_link(r["path"], cfg)
            text = todo["text"]
            if todo["due"]:
                lines.append(f"- [ ] {todo['due']} {text} {link}")
            else:
                lines.append(f"- [ ] {text} {link}")
        lines.append("")

    if important:
        lines.append("## 重要")
        for r in important:
            link = _note_link(r["path"], cfg)
            lines.append(f"- 重要度{r['importance']} {r['time_short']} {link}")
        lines.append("")

    return "\n".join(lines)


def regenerate_daily_note(date: str, cfg: Config) -> Path | None:
    """指定日(YYYY-MM-DD)の 日次/<date>.md を再生成する。
    その日の録音ノートが無ければ何もせず None を返す。"""
    notes = _list_recording_notes_for_date(cfg, date)
    if not notes:
        return None
    recordings: list[dict] = []
    for p in notes:
        fm, _ = _parse_note(p)
        recordings.append(_parse_recording_meta(fm, p))
    recordings.sort(key=lambda r: (r["time"], r["path"].name))
    out_dir = cfg.vault / _DAILY_DIR
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{date}.md"
    out_path.write_text(_render_daily_note(date, recordings, cfg), encoding="utf-8")
    return out_path


# -------------------- ③ 一覧再生成 --------------------


def _collect_all_recordings(cfg: Config) -> list[dict]:
    out: list[dict] = []
    for p in _list_recording_notes(cfg):
        fm, body = _parse_note(p)
        meta = _parse_recording_meta(fm, p)
        meta["body"] = body
        out.append(meta)
    return out


def _render_todo_index(recordings: list[dict], cfg: Config) -> str:
    """一覧/ToDo.md の本文。期限ありを直近順に、期限なしは録音新しい順に。"""
    todos_with_due: list[tuple[str, str, dict, dict]] = []  # (due, text, todo, recording)
    todos_without_due: list[tuple[str, dict, dict]] = []
    for r in recordings:
        for todo in _extract_todos(r["body"]):
            if todo["due"]:
                todos_with_due.append((todo["due"], todo["text"], todo, r))
            else:
                todos_without_due.append((todo["text"], todo, r))
    todos_with_due.sort(key=lambda t: (t[0], t[3]["date"], t[3]["time"]))
    # 期限なしは「録音が新しい順」
    todos_without_due.sort(
        key=lambda t: (t[2]["date"], t[2]["time"]), reverse=True
    )

    total = len(todos_with_due) + len(todos_without_due)
    fm = {
        "title": "ToDo一覧",
        "type": "一覧",
        "tags": ["一覧", "ToDo"],
        "total": total,
        "generated_at": _now_iso(),
    }
    fm_text = yaml.safe_dump(
        fm, allow_unicode=True, sort_keys=False, default_flow_style=False
    ).rstrip()
    lines: list[str] = []
    lines.append("---")
    lines.append(fm_text)
    lines.append("---")
    lines.append("")
    lines.append(_GENERATED_MARKER)
    lines.append("")
    lines.append("# ToDo一覧")
    lines.append("")
    lines.append(f"全 {total} 件(完了済みを除く)")
    lines.append("")

    lines.append(f"## 期限あり({len(todos_with_due)})")
    if not todos_with_due:
        lines.append("- (なし)")
    else:
        for due, text, _todo, r in todos_with_due:
            link = _note_link(r["path"], cfg)
            lines.append(f"- [ ] {due} {text} {link}")
    lines.append("")

    lines.append(f"## 期限なし({len(todos_without_due)})")
    if not todos_without_due:
        lines.append("- (なし)")
    else:
        for text, _todo, r in todos_without_due:
            link = _note_link(r["path"], cfg)
            lines.append(f"- [ ] {text} {link} ({r['date']} {r['time_short']})")
    lines.append("")

    return "\n".join(lines)


def _render_important_index(recordings: list[dict], cfg: Config) -> str:
    """一覧/重要度高.md の本文。重要度 4-5 の録音を新しい順に。"""
    pool = [r for r in recordings if r["importance"] >= 4]
    pool.sort(key=lambda r: (r["date"], r["time"]), reverse=True)
    by_score: dict[int, list[dict]] = {5: [], 4: []}
    for r in pool:
        score = 5 if r["importance"] >= 5 else 4
        by_score[score].append(r)

    fm = {
        "title": "重要度高",
        "type": "一覧",
        "tags": ["一覧", "重要"],
        "total": len(pool),
        "generated_at": _now_iso(),
    }
    fm_text = yaml.safe_dump(
        fm, allow_unicode=True, sort_keys=False, default_flow_style=False
    ).rstrip()
    lines: list[str] = []
    lines.append("---")
    lines.append(fm_text)
    lines.append("---")
    lines.append("")
    lines.append(_GENERATED_MARKER)
    lines.append("")
    lines.append("# 重要度高")
    lines.append("")
    lines.append(f"重要度 4-5 の録音 全 {len(pool)} 件")
    lines.append("")

    for score in (5, 4):
        items = by_score[score]
        lines.append(f"## 重要度 {score}({len(items)})")
        if not items:
            lines.append("- (なし)")
        else:
            for r in items:
                link = _note_link(r["path"], cfg)
                doms = " ".join(f"#{d}" for d in r["domains"])
                lines.append(
                    f"- {r['date']} {r['time_short']} {link} {doms}".rstrip()
                )
        lines.append("")

    return "\n".join(lines)


def _build_todo_entries_for_reminders(recordings: list[dict]) -> list[dict]:
    """recordings の body から ToDo を抽出して reminders.write_calendar に渡す形に。"""
    out: list[dict] = []
    for r in recordings:
        for i, todo in enumerate(_extract_todos(r["body"])):
            out.append(
                {
                    "uid": reminders.todo_uid(r["path"].stem, i),
                    "summary": todo["text"],
                    "due": todo["due"],
                    "description": (
                        f"録音 {r['date']} {r['time_short']} (注: {r['path'].stem}) より"
                    ),
                }
            )
    return out


def regenerate_index_notes(cfg: Config) -> dict[str, Path]:
    """一覧/ToDo.md と 一覧/重要度高.md を Vault 全スキャンで再生成する。
    `cfg.reminders_enabled` が True なら _reminders/todos.ics も書く。
    返り値: {"todo": Path, "important": Path, "ics"?: Path}"""
    recordings = _collect_all_recordings(cfg)
    out_dir = cfg.vault / _INDEX_DIR
    out_dir.mkdir(parents=True, exist_ok=True)

    todo_path = out_dir / "ToDo.md"
    todo_path.write_text(_render_todo_index(recordings, cfg), encoding="utf-8")

    important_path = out_dir / "重要度高.md"
    important_path.write_text(
        _render_important_index(recordings, cfg), encoding="utf-8"
    )

    out: dict[str, Path] = {"todo": todo_path, "important": important_path}
    if cfg.reminders_enabled:
        ics_entries = _build_todo_entries_for_reminders(recordings)
        out["ics"] = reminders.write_calendar(ics_entries, cfg)
    return out


# -------------------- ④ 一括 (録音1件の処理後に呼ぶ用) --------------------


def aggregate_after_note(
    structured: dict, audio_path: Path, cfg: Config
) -> dict:
    """1録音ノートが書かれた直後に呼ぶフルパイプライン。

    1. skeleton 生成(人物/トピック/場所)
    2. その日の日次ノート再生成
    3. 一覧 (ToDo, 重要度高) 再生成

    返り値はログ用のサマリ。"""
    skeletons = ensure_entity_skeletons(structured or {}, cfg)
    date = audio_path.parent.name  # YYYY-MM-DD
    daily = regenerate_daily_note(date, cfg)
    indexes = regenerate_index_notes(cfg)
    return {
        "skeletons": skeletons,
        "daily": daily,
        "indexes": indexes,
    }


def aggregate_full(cfg: Config) -> dict:
    """全 Vault スキャン版。

    - skeleton: 全録音ノートを舐めてエンティティを抽出 → 不足分作成
    - daily: 録音が存在する全日付について再生成
    - indexes: 一覧2本を再生成
    """
    recordings = _collect_all_recordings(cfg)

    # Skeleton: 各録音 frontmatter の counterpart/topics/locations をかき集める
    pseudo_structured = {
        "contexts": [
            {
                "counterpart": r["counterpart"],
                "topics": r["topics"],
                "locations": r["locations"],
            }
            for r in recordings
        ]
    }
    skeletons = ensure_entity_skeletons(pseudo_structured, cfg)

    dates = sorted({r["date"] for r in recordings})
    dailies: list[Path] = []
    for date in dates:
        out = regenerate_daily_note(date, cfg)
        if out:
            dailies.append(out)
    indexes = regenerate_index_notes(cfg)
    return {
        "skeletons": skeletons,
        "dailies": dailies,
        "indexes": indexes,
        "scanned": len(recordings),
    }
